#!/data/data/com.termux/files/usr/bin/sh

if [ ! -d /sdcard/htdocs ]
then
    mkdir /sdcard/htdocs
fi

ACMD="$1"

case $ACMD in
start)
    echo "Start Apache.."
    apachectl start
    echo "Start MySQL/MariaDB.."
    mariadbd-safe &
    sleep 3
    echo "Open browser: http://localhost:8080/"
    termux-open-url http://localhost:8080/
    ;;
start-ssl)
    if ! openssl x509 -checkend 86400 -noout -in /data/data/com.termux/files/usr/etc/apache2/server.crt
    then
      echo "SSL certificate has expired."
      echo "Creating a new SSL certificate.."
      cd ~/ && openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt -days 365 -nodes -subj '/CN=localhost'
      mv -f server.crt $PREFIX/etc/apache2/server.crt
      mv -f server.key $PREFIX/etc/apache2/server.key
    fi
    echo "Start Apache.."
    apachectl restart
    echo "Start MySQL/MariaDB.."
    mariadbd-safe &
    sleep 3
    echo "Open browser: https://localhost:8443/"
    termux-open-url https://localhost:8443/
    ;;
stop)
    apachectl stop
    pgrep mariadb && pkill mariadb
    ;;
uninstall)
    echo "Are you absolutely sure?"
    echo ""
    echo "This action will permanently delete all webserver data (Apache, MySQL/MariaDB, PHP, Composer) and cannot be undone."
    echo ""
    read -p "Do you want to continue? (y/n) " REPLY
    if [ $REPLY = "y" ]
    then
      pkg uninstall apache2 php openssl mariadb -y
      cd ~/ && rm -f -rf tamp && rm -f $PREFIX/bin/tamp
    fi
    ;;
*)
    echo "TAMP (Termux, Apache, MariaDB, PHP) v1.0"
    echo "by github.com/sekedus"
    echo " "
    echo "commands:"
    echo " start          Start tamp, localhost:8080"
    echo " start-ssl      Start tamp with SSL, port :8443"
    echo " stop           Stop tamp"
    echo " uninstall      Uninstall tamp"
esac
