#!/data/data/com.termux/files/usr/bin/sh

if [ ! -d /sdcard/htdocs ]
then
    mkdir /sdcard/htdocs
fi

ACMD="$1"

case $ACMD in
start)
    echo "Start Apache.."
    apachectl start
    echo "Start MySQL/MariaDB.."
    mariadbd-safe &
    sleep 3
    echo "Open browser: http://localhost:8080/"
    termux-open-url http://localhost:8080/
    ;;
start-ssl)
    if ! openssl x509 -checkend 86400 -noout -in /data/data/com.termux/files/usr/etc/apache2/server.crt
    then
      echo "SSL certificate has expired."
      echo "Creating a new SSL certificate.."
      cd ~/ && openssl req -x509 -newkey rsa:2048 -keyout server.key -out server.crt -days 365 -nodes -subj '/CN=localhost'
      mv -f server.crt $PREFIX/etc/apache2/server.crt
      mv -f server.key $PREFIX/etc/apache2/server.key
    fi
    echo "Start Apache.."
    apachectl restart
    echo "Start MySQL/MariaDB.."
    mariadbd-safe &
    sleep 3
    echo "Open browser: https://localhost:8443/"
    termux-open-url https://localhost:8443/
    ;;
stop)
    apachectl stop
    pgrep mariadb && pkill mariadb
    ;;
update)
    if [ ! -d ~/tamp ];
    then
    echo "TAMP directory not found."
      git clone https://github.com/sekedus/tamp.git
    fi
    cd $HOME/tamp
    git remote update
    STATUS=$(git status -uno | grep 'Your branch is up to date')
    echo "Check for TAMP updates.."
    if [ -z "$STATUS" ]; then
      git reset --hard HEAD
      git pull
      sh update
    else
      echo "\033[0;33mAlready up to date.\033[0m"
    fi
    ;;
uninstall)
    echo "Are you absolutely sure?"
    echo ""
    echo "This action will permanently delete all webserver data (Apache, MySQL/MariaDB, PHP, Composer) and cannot be undone."
    echo ""
    read -p "Do you want to continue? (y/n) " REPLY
    if [ $REPLY = "y" ]
    then
      rm $PREFIX/etc/apache2/server.crt
      rm $PREFIX/etc/apache2/server.key
      apt purge apache2 php openssl-tool mariadb -y
      apt autoremove -y
      cd ~/ && rm -rf tamp && rm $PREFIX/bin/tamp
      echo "TAMP has been successfully uninstalled."
    else
      echo "Abort."
    fi
    ;;
*)
    echo "TAMP (Termux, Apache, MariaDB, PHP) v1.0"
    echo "by github.com/sekedus"
    echo " "
    echo "commands:"
    echo " start          Start TAMP, localhost:8080"
    echo " start-ssl      Start TAMP with SSL, port :8443"
    echo " stop           Stop TAMP"
    echo " update         Update TAMP"
    echo " uninstall      Uninstall TAMP"
esac

# tamp
